name: Publish to PyPI with uv

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      run: pip install uv

    - name: Create virtual environment
      run: uv venv venv

    - name: Install build dependencies
      run: |
        source venv/bin/activate
        uv pip install build twine

    - name: Build package
      run: |
        source venv/bin/activate
        python -m build

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        source venv/bin/activate
        twine upload dist/* --username __token__ --password $PYPI_TOKEN
